[database]
    name = 'database'
    username = 'awesome-user'
    password = 'something'

[solana]
    network = 'devnet'
    api_url = 'https://api.devnet.solana.com'
    wallet = 'server_publicKey'
    private_key = ''
    custom = 'reward_address'